[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
core = { path = "../core" }
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = { version = "2.0.38", features = ["full", "extra-traits"] }
